on: [push]
name: Run Tests across GHC versions
jobs:
  generateMatrix:
    name: "Generate matrix from cabal"
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Extract the tested GHC versions
        id: set-matrix
        uses: kleidukos/get-tested@v0.1.8.0
        with:
          cabal-file: ghc-hs-meta.cabal
          ubuntu-version: latest
          version: 0.1.7.0
  test:
    name: GHC ${{ matrix.ghc }}
    needs: generateMatrix                                                                                               
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.generateMatrix.outputs.matrix) }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
      - run: cabal test
