on: [push]
name: Run Tests across GHC versions
jobs:
  generateMatrix:
    name: "Generate matrix from cabal"
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout base repo
        uses: actions/checkout@v2
      - name: Extract the tested GHC versions
        id: set-matrix
        run: |
          wget https://github.com/Kleidukos/get-tested/releases/download/v$GET_TESTED/get-tested-$GET_TESTED-linux-amd64 -O get-tested
          chmod +x get-tested
          ./get-tested --ubuntu ghc-hs-meta.cabal >> $GITHUB_OUTPUT
        env:
          GET_TESTED: "0.1.5.0"
  test:
    name: GHC ${{ matrix.ghc }}
    needs: generateMatrix                                                                                               
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.generateMatrix.outputs.matrix) }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
      - run: cabal test
