on: [push]
name: Run Tests across GHC versions
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ghc:
          - 8.10.7
          - 9.0.2
          - 9.2.8
          - 9.4.5
          - 9.6.2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
      - run: cabal test
