on: [push]
name: Run Tests across GHC versions
jobs:
  ghc8107:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: '8.10.7'
      - run: cabal test

  ghc902:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: '9.0.2'
      - run: cabal test

  ghc924:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: '9.2.4'
      - run: cabal test

  ghc941:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: '9.4.1'
      - run: cabal test
